spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/capdesign
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB

logging.level:
  org.hibernate.SQL: debug

security:
  secretKey: CAPSTONE_DESIGN_SECRET

file:
  dir: /Users/ajyng/desktop/imageFile/